include $(APOLLODIR)/Compiler_Flag

ccflags-y := -I$(SDKDIR)/include \
             -I$(SDKDIR)/system/include \
             -I$(SDKDIR)/src/module/pkt_redirect \
             -I$(SDKDIR)/src/module/ca_rtk_epon_drv \
             -I$(ROOTDIR)/ca_packages/ca-network-engine/1.0-r0/ca-network-engine-1.0 \
             -I$(ROOTDIR)/ca_packages/ca-pon-mac/1.0-r0/ca-pon-mac-1.0 \
             -I$(ROOTDIR)/ca_packages/ca-scfg/1.0-r0/ca-scfg-1.0 \
             $(PON_CFLAGS) -DCONFIG_SDK_KERNEL_LINUX

obj-m += ca-rtk-epon-drv.o
ca-rtk-epon-drv-objs := ca_rtk_epon_drv_main.o
