obj-y += rtk_proc.o netdev_reset.o
obj-$(CONFIG_RTK_NETLOG)		+= netlog.o
obj-$(CONFIG_USB)	+= rtk_usb_phy.o
obj-$(CONFIG_RTK_KERNEL_OMD) += rtl_signalCapture.o
obj-$(CONFIG_RTK_HS_UART) += hs_uart.o
